In [35]:
import pandas as pd
import numpy as np

In [56]:
dataset = pd.read_csv("out.csv")

In [64]:
dataset["release_year"][0] >= 2016 and dataset["release_year"][0] < 2020


True

In [69]:
dataset["rap_era"] = ["None"]*len(dataset)
for i in range(len(dataset)):
    if dataset["release_year"][i] >= 1986 and dataset["release_year"][i] < 1992:
        dataset["rap_era"].replace(["None"], ["1986-1991"])
    elif dataset["release_year"][i] >= 1992 and dataset["release_year"][i] < 1996:
        dataset["rap_era"].replace(["None"], ["1992-1995"])
    elif dataset["release_year"][i] >= 1996 and dataset["release_year"][i] < 2000:
        dataset["rap_era"].replace("None", "1996-1999")
    elif dataset["release_year"][i] >= 2000 and dataset["release_year"][i] < 2004:
        dataset["rap_era"].replace("None", "2000-2003")
    elif dataset["release_year"][i] >= 2004 and dataset["release_year"][i] < 2008:
        dataset["rap_era"].replace("None", "2004-2007")
    elif dataset["release_year"][i] >= 2008 and dataset["release_year"][i] < 2012:
        dataset["rap_era"].replace("None", "2008-2011")
    elif dataset["release_year"][i] >= 2012 and dataset["release_year"][i] < 2016:
        dataset["rap_era"].replace("None", "2012-2015")
    elif dataset["release_year"][i] >= 2016 and dataset["release_year"][i] < 2020:
        dataset["rap_era"].replace("None", "2016-2019")
    elif dataset["release_year"][i] >= 2020:
        dataset["rap_era"].replace(["None"], ["2020-Present"])    
    print(dataset["rap_era"][i])

None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None


None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None


None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None


None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None


None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None


None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None


None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None


None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None


None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None


In [66]:
dataset

Unnamed: 0  danceability  \
0                                                  Swang         0.681   
1                                223's (feat. 9lokknine)         0.932   
2                                              EARFQUAKE         0.554   
3                                      Sanguine Paradise         0.729   
4                                          Chucky Cheese         0.890   
...                                                  ...           ...   
14850                                     Alone in Vegas         0.459   
14851                                       The Epilogue         0.450   
14852                            Detonate (feat. M.O.P.)         0.426   
14853  Born In LA (featuring Chace Infinite & Sick Ja...         0.416   
14854                                       Ye Not Crazy         0.862   

       energy  key  loudness  mode  speechiness  acousticness  \
0       0.314    8    -9.319     1       0.0581      0.200000   
1       0.547    0    -7.787     0       0.3330      0.038800   
2       0.498    9    -8.866     1       0.0685      0.230000   
3       0.603    6    -6.736     0       0.0666      0.094800   
4       0.542   10    -4.826     0       0.3140      0.523000   
...       ...  ...       ...   ...          ...           ...   
14850   0.788    6    -3.438     1       0.1630      0.002880   
14851   0.984   10    -2.472     0       0.3630      0.120000   
14852   0.772    9    -6.187     1       0.2260      0.000991   
14853   0.907    7    -3.583     1       0.0646      0.001780   
14854   0.547    8    -9.557     1       0.3330      0.144000   

       instrumentalness  liveness  valence    tempo  duration_ms  \
0              0.000010    0.1000    0.166  139.992       208120   
1              0.000000    0.0924    0.695   94.998       176640   
2              0.000006    0.7950    0.413   79.635       190067   
3              0.000000    0.1130    0.207  134.972       243976   
4              0.000000    0.1230    0.565   78.458       165293   
...                 ...       ...      ...      ...          ...   
14850          0.000000    0.1610    0.320   78.832       271533   
14851          0.000013    0.2970    0.488   80.596       190000   
14852          0.000000    0.2550    0.546  159.968       196260   
14853          0.000000    0.0771    0.246   79.648       277347   
14854          0.000000    0.0691    0.645  145.191       226759   

       release_year rap_era  
0              2016    None  
1              2019    None  
2              2019    None  
3              2019    None  
4              2018    None  
...             ...     ...  
14850          2011    None  
14851          2011    None  
14852          2015    None  
14853          2007    None  
14854          2022    None  

[14855 rows x 15 columns]

In [93]:
X = dataset.iloc[:,1:13].values
y = dataset.iloc[:, 13].values

In [94]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [111]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=1000, random_state=530)
classifier.fit(X_train, y_train)
prediction = classifier.predict(X_test)

In [112]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, prediction))
print(classification_report(y_test, prediction))
print(accuracy_score(y_test, prediction))


[[  0   0   0 ...   1   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ... 225  27   3]
 [  0   0   0 ... 150  33   3]
 [  0   0   0 ...  69  20   2]]
              precision    recall  f1-score   support

        1986       0.00      0.00      0.00         1
        1988       0.00      0.00      0.00         3
        1990       0.00      0.00      0.00         2
        1991       0.00      0.00      0.00         5
        1992       0.00      0.00      0.00         1
        1993       0.00      0.00      0.00         7
        1994       0.00      0.00      0.00        13
        1995       0.33      0.12      0.18         8
        1996       0.11      0.08      0.09        25
        1997       0.29      0.12      0.17        17
        1998       0.36      0.14      0.20        29
        1999       0.17      0.09      0.12        33
        2000       0.10      0.08      0.09        25
        2001       0.10      0.08      0.09        

/Users/mythreyavangapandu/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/mythreyavangapandu/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/mythreyavangapandu/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_